[package]
description = "ğŸ—‘ï¸"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "toke"
version = "0.20220721.0-dev"

[dependencies]
arcane = { path = "../arcane", version = "0.20220721.0-dev" }

[lib]
path = "/dev/null"
